#!/bin/sh
# -----------------------------------------------------------------------------
#             
# Copyright 2013-2019 lispers.net - Dino Farinacci <farinacci@gmail.com>
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.    
# 
# -----------------------------------------------------------------------------
#
# build-xtr
#
# Build the lisp-xtr go binary for ubuntu Linux or Alpine Linux.
# 
# -----------------------------------------------------------------------------

if [ "$1" = "" ] ; then
    echo "Build go binary lisp-xtr ..."
    go build -o lisp-xtr xtr.go ipc.go lisp.go lml.go
    exit
fi
if [ "$1" = "alpine" ] ; then
    echo "Build go binary lisp-xtr.alpine ..."
    go build -o lisp-xtr.alpine xtr.go ipc.go lisp.go lml.go
    exit
fi

#
# Fall through.
#    
echo "Nothing built"
exit
