#!/bin/bash
#------------------------------------------------------------------------------
#
# liar
#    
# Wrapper script to call "python3 liar.py" which resides in the same directory
# as this script.
#
# Usage: ./liar [-quic] <eid> <rloc> <ms> <ms-key>
#
#------------------------------------------------------------------------------

FILE=""
if [ -f ./liar.py ]; then
    python3 -Wignore -u ./liar.py $*
    exit
fi
if [ -f ./liar.pyo ]; then
    python2 -Wignore -u -O ./liar.pyo $*
    exit
fi
if [ -f ./liar.pyc ]; then
    python3.8 -O ./liar.pyc $*
    exit
fi

echo "Cannot find liar.py* executable"

