#!/bin/tcsh
# -----------------------------------------------------------------------------
#             
# Copyright 2013-2019 lispers.net - Dino Farinacci <farinacci@gmail.com>
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.    
# 
# -----------------------------------------------------------------------------
#
# lig
#
# Just a wrapper for lisp-lig.py.
#
# -----------------------------------------------------------------------------

set EID="$1"
shift
set FLAGS = "-W ignore -O -u"

if (-f ./lisp-lig.py) then
    sudo python $FLAGS ./lisp-lig.py "$EID" $*
else if (-f ./lisp-lig.pyc) then
    sudo python3.8 $FLAGS ./lisp-lig.pyc "$EID" $*
else if (-f ./lisp-lig.pyo) then
    sudo python $FLAGS ./lisp-lig.pyo "$EID" $*
endif
