#!/bin/tcsh
# -----------------------------------------------------------------------------
#             
# Copyright 2013-2019 lispers.net - Dino Farinacci <farinacci@gmail.com>
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.    
# 
# -----------------------------------------------------------------------------
#
# rig
#
# Just a wrapper for lisp-rig,py. When supplying an EID with an instance-id
# (with format [<iid>]<eid>), use double quotes as in "[<iid>]<eid>".
#
# Note when looking up a distinguished-name EID use "[<iid>]'<eid>'".
#
# -----------------------------------------------------------------------------

set EID="$1"
shift
set FLAGS = "-W ignore -O -u"

if (-f ./lisp-rig.pyo) then
    sudo python $FLAGS ./lisp-rig.pyo "$EID" $*
else if (-f ./lisp-rig.pyc) then
    sudo python3.8 $FLAGS ./lisp-rig.pyc "$EID" $*
else if (-f ./lisp-rig.py) then
    sudo python $FLAGS ./lisp-rig.py "$EID" $*
endif
